### ISSUE TITLE
Argument labels '(url:)' do not match any available overloads

### ISSUE THREAD

**Issue by Meorge** [mkoehnke/WKZombie#19]
Trying to use this code:

```
import WKZombie
let url = "https://www01.swrdc.wa-k12.net/scripts/cgiip.exe/WService=wvancous71/mobilelogin.w"
let browser = WKZombie(name: "Hello")
browser.open(url: NSURL(string: url)!)
```
I get the error "Argument labels '(url:)' do not match any available overloads", from that fourth line. Any ideas how I can fix this? (This is a sample of my code - I can provide the rest if need-be)

**Comment by mkoehnke** [comment]
Hi. First of all, you need to remove the parameter name __url:__ from the _open()_ function.
Secondly, the _open()_ function doesn't actually start the process of loading the website. It returns a so called _Action_ that is responsible for doing that. Take a look at the Usage section [(Manual Actions)](https://github.com/mkoehnke/WKZombie#manual-actions) for more information.

Your code should look something like this:

```swift
let url = NSURL(string: "https://www01.swrdc.wa-k12.net/scripts/cgiip.exe/WService=wvancous71/mobilelogin.w")!
let action : Action<HTMLPage> = browser.open(url)

action.start { result in
    switch result {
    case .Success(let page): break // process page
    case .Error(let error): break  // handle error
    }
}
```
