### ISSUE TITLE
click() assumes links?

### ISSUE THREAD

**Issue by insidegui** [mkoehnke/WKZombie#23]
I have an use case where I need to click a `<button>` on the page. I tried using `>>> click()`, but It looks like that action assumes the target to be an `<a>` tag. How can I use WKZombie to click a button on the webpage?

**Comment by mkoehnke** [comment]
I see your problem. No, with the current implementation, only Links are supported by the click method. I haven't thought this through, but one possible solution would be to move most of the HTMLLink implementation into a base class for "clickable" objects and create an additional HTMLButton class. Then, the click() method needs to be adjusted to take "clickable" objects as parameter.

**Comment by insidegui** [comment]
It would be good to have that since the impossibility to click links made me have to implement what I wanted manually instead of using WKZombie :(

**Comment by mkoehnke** [comment]
@insidegui I've created a pull request where I introduce a *press()* method, that you can use to click a <button>. Note: It's not extensively tested yet. See #24. Let me know if that works for you.

**Comment by mkoehnke** [comment]
Fixed with #24

**Comment by fishfisher** [comment]
Hi! What was the solution here? I'm trying to get click() to work, but I am not able to figure it out. I am able to get something by using >>> execute("document.getElementById(\"buttonLogin\").click();"), but the chaining after that does not work.
