### ISSUE TITLE
Using === doesn't compile

### ISSUE THREAD

**Issue by mattti** [mkoehnke/WKZombie#29]
Hi!
I'm trying to use WKZombie with following code:
```   
func getMainPage(username: String, password: String){
        let url = NSURL(string:"https://abc.com/cde")!
        browser.open(url)
        >>> browser.get(by: .Id("Id"))
        >>> browser.setAttribute("value", value: username)
        >>> browser.get(by: .Id("Pass"))
        >>> browser.setAttribute("value", value: password) 
       browser.inspect()
        >>> browser.execute("dothejob();")
        browser.inspect()
        >>> browser.getAll(by: .Id("Some_Element"))
        === handleResult
}
```

However XCode gives me 

`Binary operator '===' cannot be applied to operands of type 'Action<[HTMLElement]>' (aka 'Action<Array<HTMLElement>>') and '(Result<HTMLTableRow>) -> ()'`

The handleResult method is identical to the method in the example project.
I haven't tried the whole example project, but when I replace my file with the contents of LoginViewController.swift from the example, I get the same warning.

What am I missing?

**Comment by mkoehnke** [comment]
@mattti Hi! Your code looks good and it compiles with the latest revision. Are you using CocoaPods by any chance? I made some changes to the === Operator recently and it's not included in the 0.9.3 release. I usually collect a few changes before I release a new version. However, you might get around this issue by using :branch => "master" in your ``Podfile``.

**Comment by mattti** [comment]
@mkoehnke That helped. Thanks!

**Comment by jaloo555** [comment]
Hi,
I tried using WKZombie for this code

browser.open(url)
    >>> browser.get(by: .Id("Username"))
    >>> browser.setAttribute("value", value: username)
    >>> browser.get(by: .Id("Password"))
    >>> browser.setAttribute("value", value: password)
    >>> browser.get(by: .Id("site-login-form"))
    >>> browser.submit(then: .Wait(2.0))
    >>> browser.get(by: .Contains("href", "#studentmyday/schedule"))
    >>> browser.click(then: .Wait(2.0))
    >>> browser.getAll(by: .Id("accordionSchedules"))
    === handleResult

and it returns the same error as above.  All the methods are the same. Any ideas? 
Thanks!
