### ISSUE TITLE
Limited to iOS 9.1?

### ISSUE THREAD

**Issue by ceeK** [mkoehnke/WKZombie#30]
Is there a specific reason this pod can't be used below iOS 9? I have an iOS 8 and up project that could benefit from WKZombie :)

**Comment by mkoehnke** [comment]
@ceeK Hi Chris. There are some small iOS9 dependencies in the WKWebView area. Those could be  easily resolved, I think. But the main reason for this limitation is that I didn't want to invest too much time in maintaining multiple deployment targets (considering how buggy iOS8 seems to be). However, feel free to make a pull request and I'll have a look! Thanks.

**Comment by mkoehnke** [comment]
Closed due to inactivity.
