### ISSUE TITLE
Get all HTMLRows in HTMLTable on page

### ISSUE THREAD

**Issue by CaptainMack** [mkoehnke/WKZombie#41]
Hi,

I'm trying to convert my backend scraper to an on-device scraper using your library, but I'm finding it hard to understand the documentation without examples, how would one use WKZombie to login and get a HTML Table, and how do you debug it? I can't seem to get document.title to print anything other than nil. I'm opening an URL that will redirect me to a page, where I can login.

I have the following code for now:

```
func testScraper(_ url: URL, user: String, password: String) {
    open(url)
        >>> get(by: .id("username"))
        >>> setAttribute("value", value: user)
        >>> get(by: .id("password"))
        >>> setAttribute("value", value: password)
        >>> get(by: .name("f"))
        >>> submit(then: .wait(2.0))
        >>> getAll(by: .contains("class", "DataSelect"))
        === handleResult
}
```

But I'm just getting a "error loading page: Not found" when printing the result, but I can't debug it without knowing if it has been redirected before It tries to get the table and forth? And do you recommend using browser.\* instead of the >>> operators? I'm having a very difficult time adjusting the example code to my own use-case, as I keep getting errors like "operands here have types 'Action<HTMLElement>' and '([HTMLElement]) -> ()'.

All the best,
Christian

**Comment by mkoehnke** [comment]
Hi Christian,

Thank you for trying out WKZombie. You're absolutely right. The documentation and better debugging is something that is always on the TODO list, but you know how it is 😬. Will try to improve that soon.

Anyway. Do you have the Logger enabled? If so, you should see output like this:

```
..

.SCRIPT
getElementByXpath("//*[@id='username']").setAttribute("value", "..."); document.documentElement.outerHTML;
[]

.SCRIPT
getElementByXpath("//*[@id='password']").setAttribute("value", "..."); document.documentElement.outerHTML;
[]

.SCRIPT
document.form2.submit();
[..................................]

...
```
 This should give you a hint of what action was executed before it failed. Another way is to call the  `dump()` method, which prints the current content (e.g. HTML) to the console.

What other way of debugging would you like to see in WKZombie? I am always open for suggestions and pull requests of course 🙃

Hope that helps,
Mathias

**Comment by CaptainMack** [comment]
Thanks for your long and helpful reply @mkoehnke,

How does WKZombie handle redirect? E.g.

I open URL #1, which immediately redirects me to URL #2, but the logger only shows the first page, which is empty

    [.<html><head></head><body></body></html>...]

I see that there's a wait option for postActions only, is there something else for opening URLs? or awaiting redirection?

**Comment by avisual** [comment]
Run the inspect command after your execute. I had this same issue with an angular form and model

execute("loginPassword.value='password'")
execute("angular.element($('#loginPassword')).triggerHandler('input')")
execute("angular.element($('#submitButton')).triggerHandler('click')")
inspect

Hope this helps

**Comment by mkoehnke** [comment]
Hi Christian,

I am so sorry about the late response. I have too much on my plate right now :-(

Did you find a solution for this issue?

Can you elaborate a bit more on why you think that webpages treat WKZombie as a JavaScript-disabled browser? Also, the form-snippet you've posted, is that the actual HTML source code or did you modify it to try working around that issue?

I would like to reproduce this issue on my side to hopefully come up with a solution.

Thanks!

**Comment by mkoehnke** [comment]
Hope that helped. Will close this ticket for now due to inactivity. Feel free to reopen it if you're still seeing this issue.

**Comment by petripartanen** [comment]
Submit method wouldn't work on above mentioned form as the function requires form to have `id` or `name` attribute. 

HTMLForm.swift:69
```
internal func actionScript() -> String? {
    if let name = name {
         return "document.\(name).submit();"
    } else if let id = id {
        return "document.getElementById('\(id)').submit();"
    }
    return nil
}
```
