### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by avisual** [mkoehnke/WKZombie#43]
Is there any way of doing this?

**Comment by mkoehnke** [comment]
Hi @avisual . Sorry, there's currently no way to do this. But this is definitively a very important feature to have. I am surprised that nobody asked that before. I'll publish a branch (hopefully tomorrow) with the ability to handle Authentication Challenges. Stay tuned.

**Comment by avisual** [comment]
Cool Thanks, 

How would I add that to a new Xcode project? any chance of a pointer as been using swift for about 5 days

**Comment by mkoehnke** [comment]
Take a look at #45 and the branch `authentication`. It's not final yet, but you can try it out.

For enabling basic authentication, just add an authentication handler to your WKZombie instance like this:
```swift
browser.authenticationHandler = { (challenge) -> (URLSession.AuthChallengeDisposition, URLCredential?) in
   return (.useCredential, URLCredential(user: "user", password: "passwd", persistence: .forSession))
}
```

Let me know if it works.

**Comment by avisual** [comment]
Amazing! Thanks for the prompt response. Its been a bit of an uphill climb switching from Java to Swift 3 this week.

John

**Comment by avisual** [comment]
Thanks That works great
