### ISSUE TITLE
Creating Action Functions

### ISSUE THREAD

**Issue by MasterSwift** [mkoehnke/WKZombie#47]
I want to know how do I create actions so I can continue using headless browser even after calling the function. In a sense, I want to mimic the WKZombie methods but on a parsing function.

**Comment by MasterSwift** [comment]
I also get this error sometimes. Strangely it shows up even though it has succeeded in parsing the HTML element before

```
[.......................................................................................................................................................................................................................................................................................................

Cancelling Rendering - Optional("SCRIPT\nwindow.top.location.href=\'SOME LINK THAT I PASS IN;")

MyProject[665:172765] Unable to parse.
```

**Comment by mkoehnke** [comment]
Sorry for the late response. Hope you found an answer in the meantime. If not, feel free to reopen this issue. Thanks!
