### ISSUE TITLE
HTTPS request unable to parse

### ISSUE THREAD

**Issue by avisual** [mkoehnke/WKZombie#48]
Cancelling Rendering - Optional("REQUEST\nhttps://192.168.0.1:12380/")
.2016-10-26 21:09:43.529 DYC[12587:442455] Unable to parse.

I can give you an external address to this if you need it, it is using a self sign cert just wondering how to get round this

**Comment by mkoehnke** [comment]
Hi @avisual . I haven't tried it yet, but maybe this works:

```swift
browser.authenticationHandler = { (challenge) -> (URLSession.AuthChallengeDisposition, URLCredential?) in
   return(.useCredential, URLCredential(trust: challenge.protectionSpace.serverTrust!))
}
```

Let me know. Thanks!

**Comment by avisual** [comment]
No Afraid that didn't work. same issue, tried increasing time out to 60 seconds just incase it was slow to respond.

**Comment by mkoehnke** [comment]
Hi @avisual . So, I finally found the time to test it myself. The code I've posted above should work, but only in combination with the `NSAppTransportSecurity` setting in the Info.plist. For debugging, you can set `NSAllowsArbitraryLoads` to `YES`. A better way is to use `NSExceptionDomains` like this:

<img width="422" alt="screen shot 2016-10-29 at 11 07 33 pm" src="https://cloud.githubusercontent.com/assets/1428877/19832772/38140942-9e2d-11e6-9bbe-fa8ed89c2f7a.png">

I've added a test for self signed certificates in the `authentication`-branch. Take a look.

Hope that helps.

**Comment by avisual** [comment]
REQUEST
https://xxx.xxx.xxx.xxx:12380
[.An SSL error has occurred and a secure connection to the server cannot be made.
]

<html><head></head><body></body></html>
.

**Comment by mkoehnke** [comment]
I'm not an expert regarding **App Transport Security**, but it should work with self signed certificates. Maybe it's a misconfiguration issue. Anyway, using the option `NSAllowsArbitraryLoads` should work in any case:

<img width="396" alt="screen shot 2016-10-30 at 9 08 08 pm" src="https://cloud.githubusercontent.com/assets/1428877/19839680/7adec9b0-9ee6-11e6-8985-4a42323a19c7.png">

Try it and let me know.

**Comment by mkoehnke** [comment]
Hope that helped. Will close this ticket for now due to inactivity. Feel free to reopen it if you're still seeing this issue.
