### ISSUE TITLE
Swift Package Manager - unsupported layout

### ISSUE THREAD

**Issue by rchatham** [mkoehnke/WKZombie#52]
Hi I am receiving the following whenever I try to download using SPM.

`error: the package has an unsupported layout, unexpected source file(s) found: /Users/Reid/Developer/airbnb_wishlister/Packages/WKZombie-1.0.6/Tests/Tests.swift
fix: move the file(s) inside a module`

**Comment by mkoehnke** [comment]
Hi! Thanks for reporting this! It looks like they change something with the latest release of SPM. I'll look into this.

**Comment by rchatham** [comment]
Thank you!

**Comment by mkoehnke** [comment]
Take a look at [1.0.7](https://github.com/mkoehnke/WKZombie/releases/tag/1.0.7) and let me know if it works. Thanks!

**Comment by mkoehnke** [comment]
If not fixed, please reopen.
