### ISSUE TITLE
Show network activity indicator

### ISSUE THREAD

**Issue by gbmksquare** [mkoehnke/WKZombie#55]
When `WKZombie` is loading a webpage or fetching content online, it would be good to show network activity indicator on the status bar by internally increasing and decreasing network activity count.

Or, `WKZombie` can send notifications to allow users handle network activity indicator themselves.

**Comment by mkoehnke** [comment]
Hi @gbmksquare You're absolutely right! Good point. Will think of something. Thanks!

**Comment by mkoehnke** [comment]
I added a ``showNetworkActivity`` property.  See [1.0.8](https://github.com/mkoehnke/WKZombie/releases/tag/1.0.8).

**Comment by gbmksquare** [comment]
Great!
