### ISSUE TITLE
Update to Swift 3?

### ISSUE THREAD

**Issue by odonckers** [mkoehnke/WKZombie#60]
This framework looks perfect for what I've been looking for!  The only problem is that my app is made in Swift 3, and yours seems to be older than that.  I installed the Cocoapod, and there were 99 errors!  The reason is because it needs to be updated.  So is there an update to WKZombie for Swift 3 comming anytime soon?

**Comment by fishfisher** [comment]
I'm wondering about the same thing:) Any update on this? Thanks!

**Comment by mkoehnke** [comment]
Hi @odonckers WKZombie is Swift 3.1 compatible. Maybe this helps: #61 ? Thanks!

**Comment by odonckers** [comment]
Oh!  Thank you @mkoehnke so much.  I need to learn to look for something before I ask, sorry for the inconvenience!
