### ISSUE TITLE
UI API called on a background thread - iOS 11 - Xcode 9

### ISSUE THREAD

**Issue by fishfisher** [mkoehnke/WKZombie#68]
Hi!
FYI:
WKZombie unfortunately does not work on iOS 11. The NSOperationQueue is of type USER_INITIATED and calls to WKWebView requires to be on the main thread.

With the new Main Thread Checker in XCode 9 it prints out the following in the console:

- Main Thread Checker: UI API called on a background thread: -[WKWebView isLoading]
- Main Thread Checker: UI API called on a background thread: -[WKWebView configuration]
- Main Thread Checker: UI API called on a background thread: -[WKUserContentController addScriptMessageHandler:name:]
- Main Thread Checker: UI API called on a background thread: -[WKWebView setNavigationDelegate:]
- Main Thread Checker: UI API called on a background thread: -[WKWebView loadRequest:]
- Main Thread Checker: UI API called on a background thread: -[WKWebView evaluateJavaScript:completionHandler:]

Best regards,
Erik

**Comment by mkoehnke** [comment]
Hi @fishfisher Thank you very much for reporting this! I'll have a look.

**Comment by revanthmonsanto** [comment]
Yes, We have the same issue too. Hope we have working version ASAP. The app crashes now.

**Comment by MatthiasB94** [comment]
Hi @mkoehnke any news on this? We're seeing the same issue and would love to know if you found a fix.

**Comment by mkoehnke** [comment]
Hi guys! Sorry for the late response. I am currently working on a fix. My plan is to release a new version by the end of the week. Sorry for the inconvenience. I didn‘t have much time lately to make WKZombie iOS11 compatible. For any other iOS11 related issues, please open another issue and I‘ll try to include a fix in the next release as well! Thanks!

**Comment by mkoehnke** [comment]
Hi. I've created a new release [1.1.0](https://github.com/mkoehnke/WKZombie/releases/tag/1.1.0) that should fix the crashes seen in iOS11/Xcode9. It's still a pre-release, so please let me know if that fixes the issue on your side. Thanks!
