### ISSUE TITLE
ERROR: "Result' is ambiguous for type lookup in this context" with Alamofire in same project

### ISSUE THREAD

**Issue by 14T** [mkoehnke/WKZombie#72]
Thanks for the library! 

I added WKZombie to the already existing project where [Alamofire](https://github.com/Alamofire/Alamofire) was already being used.

I found that there is a collision of keyword **Result** in both the libraries. 
Getting error: '**Result' is ambiguous for type lookup in this context**

 #71 Submitted a pull request to suggest a possible fix

**Comment by mkoehnke** [comment]
Hi @14T! Thank you for reporting this issue and submitting a pull request. I really appreciate the effort! I wouldn't move the `Result` enum to the WKZombie class though, as I consider it to be part of the module and not that particular class. In addition, the function signatures would be much harder to read. Anyway, I added a FAQ section to the README, that describes how to properly work around this issue. Let me know if that helps and what you think. Thanks again.
